// Generated by https://quicktype.io

export interface StationData {
  scrape_time: number;
  station_id: string;
  num_bikes_available: number;
  num_bikes_disabled: number;
  num_docks_available: number;
  num_docks_disabled: number;
  is_installed: number;
}
